title: Ye Min
description: Offshore wind, renewable energy, power systems, policy and sustainability.
url: "https://yeminn.com"
baseurl: ""
permalink: /blog/:title/
markdown: kramdown

# GitHub Pages/Jekyll defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: post
      author: Ye Min

exclude:
  - README.md
